### PR TITLE
#9 Ajout de la musique

### PR DESCRIPTION
**Pull request by Newyn**
Modification index.html
Création dossier audio
Création musique audio/music.ogg

### CODE REVIEW

**Comment by Yoric** [comment]
Where does the music come from?

**Comment by Newyn** [comment]
It comes from Youtube : 

http://www.youtube.com/watch?v=QmCodqJcYEM

**Comment by Yoric** [comment]
According to the law, unless you have an explicit authorization, using someone else's music (or code, or text, etc.) is forbidden. You should look for music that is available with an open license, such as a Creative Commons license.

**Comment by Yoric** [comment]
Closing until you have such a music.

**Pull request closed without merging**
