### PR TITLE
Ajout d'un game over screen

### PR DESCRIPTION
**Pull request by Lingelo**
Nous avons rajouter une pop up de fin de partie qui permet de relancer le jeu si le joueur gagne ou perd. En gardant à l'ésprit le coté graphique 8 bit.

### CODE REVIEW

**Comment by Yoric** [comment]
I will take a look. However, you will need to _rebase_ your commit before I can merge it. As it is, I cannot apply it cleanly.

**Comment by Yoric** [comment]
I like the idea.
Please make the following changes:
- rebase your commit;
- clicking anywhere outside of the modal should also restart the game;
- test if this works nicely with a blue background for the modal (RPG style).

I will take a look at the code once you have done this.

**Comment by Lingelo** [comment]
I will do this changes asap. 
- In order to rebase my futur commit I have to performed a git pull --rebase right?

**Comment by Yoric** [comment]
Exactly

**Pull request closed without merging**
